/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 out.glb --transform 
Files: out.glb [8.82MB] > E:\Programming\Projects\personal-site\public\models\out-transformed.glb [623.15KB] (93%)
*/

import React, {useRef} from 'react'
import { useGLTF } from '@react-three/drei'
import {Mesh} from "three";
import {useFrame} from "@react-three/fiber";

export function Station(props) {
  const { nodes, materials } = useGLTF('/models/out-transformed.glb')
    const meshRef = useRef<Mesh>(null!)

    let flips = 0;
    let count = 0;
    useFrame((_state, delta) => {
        if (meshRef.current) {
            meshRef.current.rotation.y += delta * 0.1;

            const dir = flips % 2 == 1 ? -1 : 1
            meshRef.current.rotation.z += dir * delta * 0.01;

            count += delta
            if (count > 1){
                flips += 1
                count = 0
            }
        }
    });

  return (
    <group {...props} dispose={null} ref={meshRef}>
      <group rotation={[0, 1.571, 0]} scale={.1} >
        <mesh geometry={nodes.Cylinder001.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cylinder001_1.geometry} material={materials['Material.003']}/>
        <mesh geometry={nodes.Cylinder001_2.geometry} material={materials['Material.002']} material-color="#00FFFF"/>
      </group>
    </group>
  )
}

useGLTF.preload('/models/out-transformed.glb')
