/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 out.glb --transform 
Files: out.glb [8.82MB] > E:\Programming\Projects\personal-site\public\models\out-transformed.glb [623.15KB] (93%)
*/
// @ts-nocheck

import React, {useRef} from 'react'
import { useGLTF } from '@react-three/drei'
import {Mesh} from "three";
import {useFrame} from "@react-three/fiber";

export function Station(props) {
  const { nodes, materials } = useGLTF('/models/out-transformed.glb')
    const meshRef = useRef<Mesh>(null!)

    useFrame((state, delta) => {
        if (meshRef.current) {
            const time = state.clock.elapsedTime;
            meshRef.current.rotation.z = Math.sin(time * .5) * 0.1;
            meshRef.current.rotation.x = Math.sin(time * .5) * 0.1;

            meshRef.current.rotation.y += delta * 0.1;
        }
    });

  return (
    <group {...props} dispose={null}>
      <group rotation={[0, 0, 0]} scale={.1} ref={meshRef}>
        <mesh geometry={nodes.Cylinder001.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cylinder001_1.geometry} material={materials['Material.003']}/>
        <mesh geometry={nodes.Cylinder001_2.geometry} material={materials['Material.002']}>
            <meshStandardMaterial
                color="#00FFFF"
                emissive="#00FFFF"
                emissiveIntensity={1.25}
                toneMapped={false}
            />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/models/out-transformed.glb')
